---
- hosts: all

  vars:
    - simulator_home:
    - simulator_dir: ~{{ console_user | default(ansible_user) }}/hazelcast-simulator
  tasks:

  - name: yum update/apt-get update
    shell: |
      yum update || true
      apt-get update || true
    become: yes

  - name: Install dstat
    ansible.builtin.package:
      name: dstat
      state: present
    become: yes

  - name: Delete simulator directory
    file:
      state: absent
      path: "{{ simulator_dir }}"

  - name: Create simulator directories
    file:
      path: "{{ item }}"
      state: directory
      mode: 0775
    loop:
       - "{{ simulator_dir }}/drivers"

  # The rscyn is can't resolve the key properly if it uses relative path, so this hack is needed.
  # https://github.com/ansible/ansible-modules-core/issues/18
  - name: Set  correct ssh key path
    set_fact:
      ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file | realpath }}"
    when: ansible_ssh_private_key_file is defined

  - name: Copy bin files
    synchronize:
      src: "{{ simulator_home }}/bin"
      dest: "{{ simulator_dir }}"

  - name: Copy conf
    synchronize:
      src: "{{ simulator_home }}/conf"
      dest: "{{ simulator_dir }}"

  - name: Copy lib
    synchronize:
      src: "{{ simulator_home }}/lib"
      dest: "{{ simulator_dir }}"

  - name: Copy user-lib
    synchronize:
      src: "{{ simulator_home }}/user-lib"
      dest: "{{ simulator_dir }}"

  - name: Copy simulator python files
    synchronize:
      src: "{{ simulator_home }}/src"
      dest: "{{ simulator_dir }}"
      rsync_opts:
        - "--exclude=__pycache__"

#uploadLibraryJar(){
#    pattern=$1
#    src="$SIMULATOR_HOME/lib/$pattern"
#    rsync --checksum -a -L -e "ssh $SSH_OPTIONS" $src $SSH_USER@$AGENT:hazelcast-simulator-$SIMULATOR_VERSION/lib
#}
#
#uploadTestLibJar(){
#    pattern=$1
#    src="$SIMULATOR_HOME/drivers/driver-$VENDOR/$pattern"
#    rsync --checksum -a -L -e "ssh $SSH_OPTIONS" $src $SSH_USER@$AGENT:hazelcast-simulator-$SIMULATOR_VERSION/drivers/driver-$VENDOR/
#}
#
#uploadToRemoteSimulatorDir(){
#    src=$1
#    target=$2
#    rsync --checksum -a -L -e "ssh $SSH_OPTIONS" $src $SSH_USER@$AGENT:hazelcast-simulator-$SIMULATOR_VERSION/$target
#}
#
## Upload Simulator JARs
#uploadLibraryJar "simulator-*"
#
## We don't copy all JARs to the AGENT to increase upload speed
## ActiveMQ libraries
#uploadLibraryJar "activemq-broker*"
#uploadLibraryJar "activemq-client*"
#uploadLibraryJar "geronimo-jms*"
#uploadLibraryJar "geronimo-j2ee*"
#uploadLibraryJar "slf4j-api*"
#uploadLibraryJar "hawtbuf-*"
#uploadLibraryJar "affinity*"
#uploadLibraryJar "jna*"
#
#uploadLibraryJar "cache-api*"
#uploadLibraryJar "commons-codec*"
#uploadLibraryJar "commons-lang3*"
#uploadLibraryJar "freemarker*"
#uploadLibraryJar "gson-*"
#uploadLibraryJar "HdrHistogram-*"
#uploadLibraryJar "jopt*"
#uploadLibraryJar "junit*"
#uploadLibraryJar "log4j*"
#uploadLibraryJar "slf4j-log4j12-*"
#
#uploadToRemoteSimulatorDir "$SIMULATOR_HOME/bin/" "bin"
#uploadToRemoteSimulatorDir "$SIMULATOR_HOME/conf/" "conf"
#uploadToRemoteSimulatorDir "$SIMULATOR_HOME/user-lib/" "user-lib/"
