---
- hosts: all
  tasks:
  - name: Installs perf
    shell: |
      sudo yum -y install perf
      sudo yum -y install git
      sudo yum -y install cmake
      sudo yum -y install make
      sudo yum -y install gcc-c++
    register: result
  - debug: msg="{{result.stdout}}"



